# test change
name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main      # For production
      - staging   # For staging
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '18.18.0'
          cache: 'npm'

      - name: Install Dependencies
        run: |
          npm install
          cd functions && npm install

      - name: Build
        run: |
          if [[ "${GITHUB_REF_NAME}" == "main" ]]; then
            npm run build:production
          else
            npm run build:staging
          fi

      - name: Create Service Account Key File
        run: |
          if [[ "${GITHUB_REF_NAME}" == "main" ]]; then
            echo '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_PRODUCTION }}' > serviceAccountKey.json
          else
            echo '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_STAGING }}' > serviceAccountKey.staging.json
          fi

      - name: Install Firebase CLI
        run: npm install -g firebase-tools@13.2.1

      - name: Debug Firebase CLI
        run: firebase --version

      - name: Deploy to Firebase
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.ref_name == 'main' && './serviceAccountKey.json' || './serviceAccountKey.staging.json' }}
        run: |
          if [[ "${GITHUB_REF_NAME}" == "main" ]]; then
            echo '{ "projects": { "default": "aafairshare" } }' > .firebaserc
            firebase use aafairshare
            firebase deploy --only hosting,functions,firestore
          else
            echo '{ "projects": { "default": "aafairshare---staging" } }' > .firebaserc
            firebase use aafairshare---staging
            firebase deploy --only hosting:aafairshare---staging,functions,firestore --project aafairshare---staging
          fi

      - name: Deployment Status
        run: |
          echo "### 🚀 Deployment Status" >> $GITHUB_STEP_SUMMARY
          echo "* Branch: ${{ github.ref_name }}" >> $GITHUB_STEP_SUMMARY
          echo "* Commit: ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
          echo "* Environment: ${{ github.ref_name == 'main' && 'Production' || 'Staging' }}" >> $GITHUB_STEP_SUMMARY 