name: Staging Deployment

on:
  push:
    branches:
      - staging
      - 'feature/**'
      - 'bugfix/**'
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.18.0'
          cache: 'pnpm'

      - name: Install pnpm
        run: npm install -g pnpm@8.15.6

      - name: Install Dependencies
        run: pnpm install

      - name: Create Environment Files
        run: |
          # Create .env.staging from secret
          echo '${{ secrets.ENV_STAGING }}' > .env.staging
          # Copy to .env for build
          cp .env.staging .env

      - name: Create Service Account Key File
        run: |
          echo '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_STAGING }}' > serviceAccountKey.staging.json

      - name: Build
        run: pnpm run build:staging

      - name: Deploy to Firebase
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ./serviceAccountKey.staging.json
        run: |
          echo '{
            "projects": {
              "default": "aafairshare---staging"
            }
          }' > .firebaserc
          pnpm exec firebase deploy --only hosting:aafairshare---staging --project aafairshare---staging

      - name: Deployment Status
        run: |
          echo "### 🚀 Staging Deployment Status" >> $GITHUB_STEP_SUMMARY
          echo "* Branch: ${{ github.ref_name }}" >> $GITHUB_STEP_SUMMARY
          echo "* Commit: ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
          echo "* Environment: Staging" >> $GITHUB_STEP_SUMMARY 