name: Dependency Updates

on:
  schedule:
    # Run weekly on Monday at 5:00 AM UTC
    - cron: '0 5 * * 1'
  workflow_dispatch:
    inputs:
      updateScope:
        description: 'Update scope'
        required: true
        default: 'minor'
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  update-dependencies:
    name: Update Dependencies
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: main
      
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.18.0'
          cache: 'pnpm'
      
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
      
      - name: Set Update Type
        id: update-type
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "type=${{ github.event.inputs.updateScope }}" >> $GITHUB_OUTPUT
          else
            echo "type=minor" >> $GITHUB_OUTPUT
          fi
      
      - name: Set Current Date
        id: current-date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
      
      - name: Create Branch
        run: git checkout -b dependency-update/${{ steps.current-date.outputs.date }}
      
      - name: Update Dependencies
        run: |
          if [ "${{ steps.update-type.outputs.type }}" = "patch" ]; then
            npx npm-check-updates -u --target patch --packageFile package.json
          elif [ "${{ steps.update-type.outputs.type }}" = "minor" ]; then
            npx npm-check-updates -u --target minor --packageFile package.json
          elif [ "${{ steps.update-type.outputs.type }}" = "major" ]; then
            npx npm-check-updates -u --target minor --packageFile package.json
          fi
      
      - name: Install Updated Dependencies
        run: pnpm install
      
      - name: Run Tests
        run: pnpm test || true

      - name: Run Build
        run: pnpm run build || true
      
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: update dependencies (${{ steps.update-type.outputs.type }} updates) - ${{ steps.current-date.outputs.date }}"
          branch: dependency-update/${{ steps.current-date.outputs.date }}
          base: main
          title: "Dependencies: ${{ steps.update-type.outputs.type }} updates - ${{ steps.current-date.outputs.date }}"
          body: |
            # Dependency Updates (${{ steps.update-type.outputs.type }})
            
            This PR updates dependencies to their latest ${{ steps.update-type.outputs.type }} versions.
            
            ## Changes
            
            ```diff
            $(git diff --color=always package.json | sed -E 's/^/    /')
            ```
            
            ## Notes
            
            - [ ] Review changes carefully
            - [ ] Test in development environment after merge
            - [ ] Check for breaking changes in major version updates
            
            This PR was automatically generated by the Dependency Updates workflow.
          labels: |
            dependencies
            automated-pr
            ${{ steps.update-type.outputs.type }}-update
          draft: ${{ steps.update-type.outputs.type == 'major' }}
      
      - name: Post Update Summary
        run: |
          echo "### 📦 Dependency Update Created" >> $GITHUB_STEP_SUMMARY
          echo "**Type:** ${{ steps.update-type.outputs.type }} update" >> $GITHUB_STEP_SUMMARY
          echo "**Date:** ${{ steps.current-date.outputs.date }}" >> $GITHUB_STEP_SUMMARY
          echo "**Branch:** dependency-update/${{ steps.current-date.outputs.date }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "A pull request has been created to update dependencies. Please review the changes before merging." >> $GITHUB_STEP_SUMMARY 