name: Dependency Updates

on:
  schedule:
    # Run weekly on Monday at 5:00 AM UTC
    - cron: '0 5 * * 1'
  workflow_dispatch:
    inputs:
      updateScope:
        description: 'Update scope'
        required: true
        default: 'minor'
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  update-dependencies:
    name: Update Dependencies
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: develop
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.18.0'
          cache: 'npm'
      
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
      
      - name: Determine Update Type
        id: update-type
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "UPDATE_TYPE=${{ github.event.inputs.updateScope }}" >> $GITHUB_ENV
          else
            echo "UPDATE_TYPE=minor" >> $GITHUB_ENV
          fi
      
      - name: Get Current Date
        id: date
        run: echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      
      - name: Create Branch
        run: git checkout -b dependency-update/${{ env.DATE }}
      
      - name: Update Dependencies
        run: |
          if [ "${{ env.UPDATE_TYPE }}" == "patch" ]; then
            npx npm-check-updates -u --target patch --packageFile package.json
          elif [ "${{ env.UPDATE_TYPE }}" == "minor" ]; then
            npx npm-check-updates -u --target minor --packageFile package.json
          elif [ "${{ env.UPDATE_TYPE }}" == "major" ]; then
            npx npm-check-updates -u --target minor --reject firebase,firebase-admin,firebase-tools --packageFile package.json
            # Only update Firebase packages in patch mode to prevent breaking changes
            npx npm-check-updates -u --target patch --filter "firebase,firebase-admin,firebase-tools" --packageFile package.json
          fi
      
      - name: Install Updated Dependencies
        run: npm install
      
      - name: Run Tests
        run: npm test || true

      - name: Run Build
        run: npm run build:staging || true
      
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: update dependencies (${{ env.UPDATE_TYPE }} updates) - ${{ env.DATE }}"
          branch: dependency-update/${{ env.DATE }}
          base: develop
          title: "Dependencies: ${{ env.UPDATE_TYPE }} updates - ${{ env.DATE }}"
          body: |
            # Dependency Updates (${{ env.UPDATE_TYPE }})
            
            This PR updates dependencies to their latest ${{ env.UPDATE_TYPE }} versions.
            
            ## Changes
            
            ```diff
            $(git diff --color=always package.json | sed -E 's/^/    /')
            ```
            
            ## Notes
            
            - [ ] Review changes carefully
            - [ ] Test in staging environment after merge
            - [ ] Check for breaking changes in major version updates
            
            This PR was automatically generated by the Dependency Updates workflow.
          labels: |
            dependencies
            automated-pr
            ${{ env.UPDATE_TYPE }}-update
          draft: ${{ env.UPDATE_TYPE == 'major' }}
      
      - name: Post Update Summary
        run: |
          echo "### 📦 Dependency Update Created" >> $GITHUB_STEP_SUMMARY
          echo "**Type:** ${{ env.UPDATE_TYPE }} update" >> $GITHUB_STEP_SUMMARY
          echo "**Date:** ${{ env.DATE }}" >> $GITHUB_STEP_SUMMARY
          echo "**Branch:** dependency-update/${{ env.DATE }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "A pull request has been created to update dependencies. Please review the changes before merging." >> $GITHUB_STEP_SUMMARY 